- name: Create a temp dir
  command: mktemp -d -t ansible.XXXXXXXXXX
  register: temp_output

- name: Set tmp_path
  set_fact:
    tmp_path: "{{ temp_output.stdout }}"

- name: Template route.yml 
  template: 
    src: route.j2.yml
    dest: "{{ tmp_path }}/route.yml" 

- name: Create the route
  command: oc create -f route.yml 
  args:
    chdir: "{{ tmp_path }}" 
  ignore_errors: yes

- name: Remove the temp directory
  file:
    path: "{{ tmp_path }}"
    state: absent
